name: IR Earnings Data Automation

on:
  workflow_dispatch:
  schedule:
    - cron: '0 9 * * *' # Every day at 9AM UTC

jobs:
  fetch-earnings:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install dependencies
        run: pip install -r requirements.txt
      - name: Run earnings fetch script
        run: python main.py
      - name: Commit earnings data
        run: |
          git config --local user.name "github-actions[bot]"
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git add output/
          git commit -m "Automated peer earnings data update" || echo "No changes to commit"
          git push
